package config

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

// ConfigGenerator generates Hysteria2 configuration files
type ConfigGenerator struct {
	template *template.Template
}

// ConfigData represents the data needed to generate a config
type ConfigData struct {
	Listen      string
	ProfileID   string
	IPAddress   string
	IPv6Address string
	Port        int
	StatsPort   int
	SNI         string
	ObfsType    string
	ObfsPassword string
	
	// TLS Configuration
	CertFile string
	KeyFile  string
	
	// Authentication
	AuthType     string
	AuthPassword string
	
	// Network Settings
	MaxConnections int
	CongestionControl string
	
	// Features
	EnableMasquerade bool
	EnableSpeedTest  bool
	
	// Outbound Settings
	OutboundBindIPv4 string
	OutboundBindIPv6 string
	
	// Use specific IP for listening (for additional IPs)
	UseSpecificIP bool
}

// NewConfigGenerator creates a new config generator
func NewConfigGenerator() (*ConfigGenerator, error) {
	tmpl, err := template.New("hysteria2_config").Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse config template: %w", err)
	}
	
	return &ConfigGenerator{
		template: tmpl,
	}, nil
}

// GenerateConfig generates a Hysteria2 configuration file
func (g *ConfigGenerator) GenerateConfig(data ConfigData, outputPath string) error {
	// Set default values
	if data.CongestionControl == "" {
		data.CongestionControl = "bbr"
	}
	if data.MaxConnections == 0 {
		data.MaxConnections = 1000
	}
	if data.AuthType == "" {
		data.AuthType = "password"
	}
	
	// Generate listen address
	if data.Listen == "" {
		data.Listen = fmt.Sprintf("%s:%d", data.IPAddress, data.Port)
	}
	
	// Set outbound binding
	if data.OutboundBindIPv4 == "" {
		data.OutboundBindIPv4 = data.IPAddress
	}
	if data.OutboundBindIPv6 == "" && data.IPv6Address != "" {
		data.OutboundBindIPv6 = data.IPv6Address
	}
	
	// Generate stats port if not set
	if data.StatsPort == 0 {
		data.StatsPort = data.Port + 10000
		if data.StatsPort > 65535 {
			data.StatsPort = 10000 + (data.Port % 10000)
		}
	}
	
	// Create output file
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()
	
	// Execute template
	if err := g.template.Execute(file, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}
	
	return nil
}

// configTemplate is the template for Hysteria2 configuration
const configTemplate = `# Hysteria2 Configuration for Profile: {{.ProfileID}}
# Generated by Shrapnel Multi-IP Manager

listen: {{.Listen}}

# TLS Configuration
tls:
  cert: {{.CertFile}}
  key: {{.KeyFile}}

# Authentication
auth:
  type: {{.AuthType}}
  {{if eq .AuthType "password"}}password: {{.AuthPassword}}{{end}}

# QUIC Configuration
quic:
  initStreamReceiveWindow: 8388608
  maxStreamReceiveWindow: 8388608
  initConnReceiveWindow: 20971520
  maxConnReceiveWindow: 20971520
  maxIdleTimeout: 30s
  maxIncomingStreams: 1024

# Bandwidth Configuration
bandwidth:
  up: 1 gbps
  down: 1 gbps

# Congestion Control
congestion:
  type: {{.CongestionControl}}

# Masquerade
{{if .EnableMasquerade}}
masquerade:
  type: proxy
  proxy:
    url: https://{{.SNI}}
    rewriteHost: true
{{end}}

# Speed Test
speedTest: {{.EnableSpeedTest}}

# Obfuscation
{{if .ObfsType}}
obfs:
  type: {{.ObfsType}}
  {{if eq .ObfsType "salamander"}}salamander:
    password: {{.ObfsPassword}}{{end}}
  {{if eq .ObfsType "gecko"}}gecko:
    password: {{.ObfsPassword}}
    minPacketSize: 500
    maxPacketSize: 1000{{end}}
{{end}}

# Outbound Configuration with IP Binding
outbounds:
  - name: direct
    type: direct
    direct:
      mode: auto
      fastOpen: true

# Traffic Statistics
trafficStats:
  listen: 127.0.0.1:{{.StatsPort}}
  secret: {{.ProfileID}}_stats_secret
`

// GenerateSystemdService generates a systemd service file for a profile
func GenerateSystemdService(profileID, configPath, binaryPath string) (string, error) {
	serviceTemplate := `[Unit]
Description=Shrapnel Multi-IP Profile: {{.ProfileID}}
After=network.target

[Service]
Type=simple
User=root
ExecStart={{.BinaryPath}} server -c {{.ConfigPath}}
Restart=on-failure
RestartSec=5s
LimitNOFILE=65536

# Security settings
NoNewPrivileges=true
PrivateTmp=true

# Environment
Environment="SHRAPNEL_PROFILE_ID={{.ProfileID}}"

[Install]
WantedBy=multi-user.target
`

	tmpl, err := template.New("systemd_service").Parse(serviceTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse systemd template: %w", err)
	}
	
	data := struct {
		ProfileID  string
		ConfigPath string
		BinaryPath string
	}{
		ProfileID:  profileID,
		ConfigPath: configPath,
		BinaryPath: binaryPath,
	}
	
	var builder strings.Builder
	if err := tmpl.Execute(&builder, data); err != nil {
		return "", fmt.Errorf("failed to execute systemd template: %w", err)
	}
	
	return builder.String(), nil
}

// ValidateConfig validates configuration data
func ValidateConfig(data ConfigData) error {
	// Validate IP address
	if data.IPAddress == "" {
		return fmt.Errorf("IP address is required")
	}
	
	// Validate port
	if data.Port < 1 || data.Port > 65535 {
		return fmt.Errorf("invalid port number: %d", data.Port)
	}
	
	// Validate SNI
	if data.SNI == "" {
		return fmt.Errorf("SNI is required")
	}
	
	// Validate auth type
	validAuthTypes := map[string]bool{
		"password": true,
		"http":     true,
		"command":  true,
	}
	if !validAuthTypes[data.AuthType] {
		return fmt.Errorf("invalid auth type: %s", data.AuthType)
	}
	
	// Validate obfs type if specified
	if data.ObfsType != "" {
		validObfsTypes := map[string]bool{
			"salamander": true,
			"gecko":      true,
		}
		if !validObfsTypes[data.ObfsType] {
			return fmt.Errorf("invalid obfs type: %s", data.ObfsType)
		}
		
		// Obfs password is required if obfs is enabled
		if data.ObfsPassword == "" {
			return fmt.Errorf("obfs password is required when obfs is enabled")
		}
	}
	
	return nil
}